### ISSUE TITLE
add variables to docker-compose

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-monitor#6]
We want to read from .env:
- version numbers
- name of external network

**Comment by Rolazo** [comment]
I already added version numbers to all of our stack:
[look](https://app.zenhub.com/workspaces/scrum-for-devops-workspace-64ae7e70d6fa5e21d8308e0a/issues/gh/giveth/devops/161)

but not from .env file.

I'll add later from our env file

**Comment by Rolazo** [comment]
@geleeroyale 
So We're aiming to updated all variables from env files, **to all our devops repos right?**
I have updated the version, I just need to updated from .env --> .env.template

**Comment by geleeroyale** [comment]
- [x] giveth-logger
- [x] giveth-monitor
- [x] giveth-vault
- [x] giveth-all

@Rolazo - I am keeping this updated list as I noticed you seem to have been successfully unblocked and finished two repos. We also need to add it to those other two. I can do that however.

**Comment by geleeroyale** [comment]
I merged and tested the PRs opened by you @Rolazo - thanks
